# src/latest_ai_development/config/tasks.yaml
research_task:
  description: >
    Conduct thorough research about {anime_topic}
    Find interesting and relevant information about recent anime developments, 
    trends, and innovations given the current year is 2025.
  expected_output: >
    A list with 10 bullet points highlighting the most significant 
    developments in {anime_topic} including new shows, technologies, 
    industry changes, and cultural impact.
  agent: anime_researcher

reporting_task:
  description: >
    Review the anime research data and transform each point into a comprehensive 
    section for an anime industry report. Include analysis on artistic trends, 
    technological advancements, and market developments.
  expected_output: >
    A complete anime industry report with detailed sections covering each research 
    point, including relevant examples, statistics, and future projections.
    Formatted as markdown without '```'
  agent: anime_analyst
  output_file: anime_report.md
